stages:
    - compile
    - secret_detection
    - test

include:
    - template: Security/Secret-Detection.gitlab-ci.yml

.build-server: &build-server
    tags:
        - build-server

variables:
    TEST_MODE: UNIT_TEST
    PRIVATE_KEY: $PRIVATE_KEY

cache:
    key:
        files:
            - package-lock.json
    paths:
        - node_modules/

compile:
    stage: compile
    image: node:24
    extends:
        - .build-server
    before_script:
        - npm ci
    script:
        - npm run clean
        - npm run format:check # prettier
        - npm run compile
        - npm run lint
        - npm run docs:check

secret_detection:
    stage: secret_detection
    image: registry.gitlab.com/security-products/secrets:6
    extends:
        - .build-server

test:
    stage: test
    image: node:24
    before_script:
        - npm ci
    extends:
        - .build-server
    script:
        - npm test
